name: Daily IPO Scrape

on:
  schedule:
    - cron: '0 15 * * *'  # 15:00 UTC = 8 AM PT
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: Commit CSV if updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.csv
          git diff-index --quiet HEAD || git commit -m "Add daily IPO CSV"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
